# This file runs the analyses for the paper using the data generated by the
# prior script. Warning: This will take a long time, due to big piecewiseSEM
# models.

# PACKAGES NECESSARY TO RUN THIS SCRIPT
required_packages   <- c("tidyverse", "lme4", "broom.mixed", "piecewiseSEM")

# SCRIPT NAMES
model_scripts  <- list.files("./syntax/models/", full.names = T)
initial_start_time <- Sys.time()
for(script in model_scripts){
  message(paste0("Running: ", script))
  start_time <- Sys.time() 
  source(script)
  message(paste0("Script time: ", 
                 round(difftime(Sys.time(), start_time, units = "secs"), 1),
                 " seconds. Total time so far: ",
                 round(difftime(Sys.time(), initial_start_time, units = "mins"), 1), 
                 " minutes." ))
}
