---
output: officedown::rdocx_document
---

```{r, include=FALSE}
library(tidyverse)
library(flextable)
library(officedown)
```

\newpage

```{r bedescrip, echo=FALSE, message=FALSE, warning=FALSE, eval=TRUE, ft.arraystretch = 1}
# Table 1
load("../output/be_descriptives_dat.RData")

be_descriptives_dat %>%
  mutate(Measure = str_replace(Measure, "2001", "2003")) %>%
  as_grouped_data(groups = "level") %>%
  flextable() %>%
  mk_par(j = "df", i = ~ !is.na(Max), value = as_paragraph(
    plot_chunk(value = df, type = "density", col = "black", 
               width = 0.8, height = .2, free_scale = TRUE)
  )) %>%
  set_header_labels(df = "Density", level = "") %>%
  # font(fontname = "Latin Modern Roman", part = "all") %>%
  fontsize(size = 11, part = "all") %>%
  set_table_properties(width = 0.8, layout = "autofit") %>%
  merge_h_range(i = c(1,8), j1 = 1, j2 = 7) %>%
  border_remove() %>%
  align(j = 3:7, align = "center", part = "all") %>%
  hline_bottom(border = officer::fp_border(width = 1)) %>%
  hline_top(border = officer::fp_border(width = 1), part = "header") %>%
  hline_top(border = officer::fp_border(width = 0.5)) %>%
  set_caption(caption = "Descriptive statistics")
```

\newpage

```{r secondstage, echo=FALSE, message=FALSE, warning=FALSE, eval=TRUE, ft.arraystretch = 0.6, ft.tabcolsep = 4}
# Table 2
source("../syntax/tables/second_stage_table.R")
s2_table %>%
  padding(part = "all", padding.left = 1, padding.right = 1, padding.top = 2, padding.bottom = 2) %>%
  set_caption(caption = "Negative binomial estimates of crime")
```

\newpage

```{r firststage, echo=FALSE, message=FALSE, warning=FALSE, eval=TRUE, ft.arraystretch = 0.8, ft.tabcolsep = 4}
# Table 3
source("../syntax/tables/first_stage_table.R")
s1_table %>%
  padding(part = "all", padding.left = 1, padding.right = 1, padding.top = 2, padding.bottom = 2) %>%
  set_caption(caption = "Linear model estimates of built environment features and collective efficacy")
```